//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intprog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grup
    {
        public int GrupId { get; set; }
        public string GrupAdi { get; set; }
        public Nullable<int> KullaniciId { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
